<?php
/**
 * Application Version
 * This file is auto-generated by GitHub Actions on each deployment.
 * DO NOT EDIT MANUALLY - it will be overwritten.
 */

// Git commit hash (short)
define('APP_VERSION', 'dev');

// Deployment timestamp
define('DEPLOY_TIME', time());
